name: PHPUnit test runner 

on:
  repository_dispatch:
    types: [phpunit_run*]

env:
  GITHUB_REF_NAME: ${{ github.event.client_payload.GITHUB_REF_NAME }}
  GITHUB_REPOSITORY: 'openeyes/openeyes'
  GITHUB_RUN_ID: ${{ github.event.client_payload.GITHUB_RUN_ID }}
  GITHUB_RUN_NUMBER: ${{ github.event.client_payload.GITHUB_RUN_NUMBER }}
  GITHUB_RUN_ATTEMPT: ${{ github.event.client_payload.GITHUB_RUN_ATTEMPT }}
  GITHUB_PULL_REQUEST: ${{ github.event.client_payload.GITHUB_PULL_REQUEST }}
  ADDITIONAL_MODULES: ${{ github.event.client_payload.additional_modules || '' }}
  COMPOSER_VERSION: 2.8.12


run-name: >
  PHPUnit
  ${{ github.event.client_payload.GITHUB_PULL_REQUEST && format('- PR {0}', github.event.client_payload.GITHUB_PULL_REQUEST) || format('- Ref {0}', github.event.client_payload.GITHUB_REF_NAME) }}
  - Run id ${{ github.event.client_payload.GITHUB_RUN_ID }} Attempt ${{ github.event.client_payload.GITHUB_RUN_ATTEMPT }}

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # run different test types in parallel
        test-type: [PHPUNIT-SAMPLE, PHPUNIT-FIXTURES]
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Checkout
        uses: actions/checkout@v4
        # populate commit message for merge commits
        # see https://currents.dev/readme/ci-setup/github-actions
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ssh-key: ${{ secrets.TKL_DEPLOY_PRIVATE_KEY }}
          ref: ${{ env.GITHUB_HEAD_REF && format('{0}', env.GITHUB_HEAD_REF) || env.GITHUB_REF_NAME }}

      # write environment variables to a docker compose .env file
      - name: Write variables to compose .env file
        run: |
          echo "TESTS_TO_RUN=${{ matrix.test-type }}" >> protected/tests/.env
          echo "PUID=$(id -u)" >> protected/tests/.env
          echo "SSH_PRIVATE_KEY='${{ secrets.TKL_DEPLOY_PRIVATE_KEY }}'" >> protected/tests/.env
          echo "BUILD_BRANCH=${{ env.GITHUB_REF_NAME }}" >> protected/tests/.env
          echo "OE_DEFAULT_BRANCH=${{ env.GITHUB_BASE_REF }}" >> protected/tests/.env
          echo "BUILD_ID=${{ env.GITHUB_REPOSITORY }}-${{ env.GITHUB_RUN_ID }}-${{ env.GITHUB_RUN_ATTEMPT}}" >> protected/tests/.env
          if [ -n "${{ env.ADDITIONAL_MODULES }}" ]; then
            echo "MODULES=${{ env.ADDITIONAL_MODULES }}" >> protected/tests/.env
          fi

      - name: Run docker
        run: |
          docker compose -f protected/tests/docker-compose.yml --env-file protected/tests/.env run --use-aliases web
